// defines potential searchterms and their mispellings so the user can be routed to the right page.
export const searchTerms = {
    "Laptop": "Laptops",
    "Laptops": "Laptops", 
    "laptop": "Laptops", 
    "laptops": "Laptops", 
    "Desktop": "Desktops", 
    "Desktops": "Desktops", 
    "desktop": "Desktops", 
    "desktops": "Desktops",  
    "Printer": "Printers",
    "Printers": "Printers",
    "printer": "Printers",
    "printers": "Printers",
    "Tv's"    : "Tv's",
    "tv's"    : "Tv's",
    "Tvs"    : "Tv's",
    "Tv"    : "Tv's",
    "tv"    : "Tv's",
    "Television"    : "Tv's",
    "television"    : "Tv's",
    "tvs"    : "Tv's",
    "tv's"    : "Tv's",
    "Projectors"    : "Projectors",
    "projectors"    : "Projectors",
    "Projector"    : "Projectors",
    "projector"    : "Projectors",
    "Phones"    : "Phones",
    "Phone"    : "Phones",
    "phones"    : "Phones",
    "phone"    : "Phones",
    "Tablets"    : "Tablets",
    "Tablet"    : "Tablets",
    "tablets"    : "Tablets",
    "tablet"    : "Tablets",
    "Cameras"    : "Cameras",
    "Camera"    : "Cameras",
    "cameras"    : "Cameras",
    "camera"    : "Cameras",
    "Gaming Consoles"    : "Consoles",
    "Gaming Console"    : "Consoles",
    "gaming consoles"    : "Consoles",
    "gaming console"    : "Consoles",
    "Consoles"    : "Consoles",
    "Console"    : "Consoles",
    "consoles"    : "Consoles",
    "console"    : "Consoles",
    "Monitors": "Monitors",
    "Monitor": "Monitors",
    "monitors": "Monitors",
    "monitor": "Monitors",
    
}